# Generated by Django 2.2.3 on 2019-07-21 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hewan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('spesies', models.CharField(max_length=200)),
                ('berat', models.IntegerField(verbose_name='Berat')),
                ('umur', models.IntegerField(verbose_name='Umur')),
            ],
        ),
        migrations.CreateModel(
            name='Kandang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('luas_kandang', models.IntegerField(verbose_name='Luas Kandang')),
            ],
        ),
        migrations.CreateModel(
            name='Orang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('nomor_telepon', models.IntegerField(verbose_name='Nomor telepon')),
            ],
        ),
        migrations.CreateModel(
            name='Pengunjung',
            fields=[
                ('orang_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kebun_binatang.Orang')),
                ('hari_berkunjung', models.DateTimeField(verbose_name='Hari berkunjung')),
            ],
            bases=('kebun_binatang.orang',),
        ),
        migrations.CreateModel(
            name='Penjaga',
            fields=[
                ('orang_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kebun_binatang.Orang')),
                ('jadwal_jaga', models.DateTimeField(verbose_name='Jadwal jaga')),
            ],
            bases=('kebun_binatang.orang',),
        ),
    ]
