# Generated by Django 2.2.3 on 2019-07-22 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livecode',
            name='materi_ptr',
        ),
        migrations.AddField(
            model_name='livecode',
            name='challenge_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ata.Challenge'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentee',
            name='nilai_rata_rata',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='orang',
            name='nomor_telepon',
            field=models.CharField(max_length=12, verbose_name='Nomor telepon'),
        ),
    ]
