# Generated by Django 2.2.3 on 2019-07-22 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ata', '0003_auto_20190722_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livecode',
            name='materi_ptr',
        ),
        migrations.AddField(
            model_name='livecode',
            name='challenge_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ata.Challenge'),
            preserve_default=False,
        ),
    ]
