# Generated by Django 2.2.3 on 2019-07-22 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ata', '0004_auto_20190722_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livecode',
            name='challenge_ptr',
        ),
        migrations.AddField(
            model_name='livecode',
            name='banyak_soal',
            field=models.IntegerField(default=None, verbose_name='Banyak soal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livecode',
            name='bobot_nilai',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=2, verbose_name='Bobot nilai'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livecode',
            name='mata_pelajaran',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ata.MataPelajaran'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livecode',
            name='materi_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ata.Materi'),
            preserve_default=False,
        ),
    ]
