# Generated by Django 2.2.3 on 2019-07-21 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('kandungan', models.TextField(verbose_name='Kandungan')),
                ('khasiat', models.TextField(verbose_name='Khasiat')),
            ],
        ),
        migrations.CreateModel(
            name='Orang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('telp', models.IntegerField(verbose_name='Nomor Telepon')),
                ('alamat', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('total_harga', models.IntegerField(verbose_name='Total harga')),
            ],
        ),
        migrations.CreateModel(
            name='Dokter',
            fields=[
                ('orang_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rumah_sakit.Orang')),
                ('bidang', models.CharField(max_length=200)),
                ('jadwal', models.DateTimeField(verbose_name='Jadwal Praktik')),
            ],
            bases=('rumah_sakit.orang',),
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('orang_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rumah_sakit.Orang')),
                ('keluhan', models.CharField(max_length=200)),
            ],
            bases=('rumah_sakit.orang',),
        ),
    ]
