# Generated by Django 2.2.3 on 2019-07-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kebun_binatang', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penjaga',
            name='jadwal_jaga',
        ),
        migrations.AddField(
            model_name='penjaga',
            name='hari_jaga',
            field=models.CharField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=None, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penjaga',
            name='mulai_jaga',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penjaga',
            name='selesai_jaga',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hewan',
            name='berat',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='hewan',
            name='umur',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kandang',
            name='luas_kandang',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
