# Generated by Django 2.2.3 on 2019-07-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kebun_binatang', '0002_kandang_isi_kandang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kandang',
            name='isi_kandang',
            field=models.TextField(),
        ),
    ]
