# Generated by Django 2.2.3 on 2019-07-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kebun_binatang', '0002_auto_20190722_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orang',
            name='nomor_telepon',
            field=models.BigIntegerField(verbose_name='Nomor telepon'),
        ),
        migrations.AlterField(
            model_name='penjaga',
            name='hari_jaga',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3),
        ),
    ]
