# Generated by Django 2.2.3 on 2019-07-24 13:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orang',
            name='join_date',
            field=models.DateField(verbose_name=datetime.datetime(2019, 7, 24, 13, 32, 28, 607365, tzinfo=utc)),
        ),
    ]
