# Generated by Django 2.2.3 on 2019-07-24 14:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190724_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orang',
            name='join_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 24, 14, 28, 47, 246284, tzinfo=utc)),
        ),
    ]
