# Generated by Django 2.2.3 on 2019-07-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20190724_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orang',
            name='join_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
