# Generated by Django 2.2.3 on 2019-07-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20190725_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orang',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
