# Generated by Django 2.2.3 on 2019-07-25 01:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20190725_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orang',
            name='join_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
