# Generated by Django 2.2.3 on 2019-07-22 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('kandungan', models.TextField(verbose_name='Kandungan')),
                ('khasiat', models.TextField(verbose_name='Khasiat')),
            ],
        ),
        migrations.CreateModel(
            name='Orang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('telp', models.CharField(max_length=12)),
                ('alamat', models.TextField(verbose_name='Alamat')),
            ],
        ),
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('total_harga', models.BigIntegerField(verbose_name='Total harga')),
                ('kumpulan_obat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dokter',
            fields=[
                ('orang_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rumah_sakit.Orang')),
                ('bidang', models.CharField(max_length=200)),
                ('hari_praktik', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3)),
                ('jam_praktik', models.TimeField(verbose_name='jadwal')),
            ],
            bases=('rumah_sakit.orang',),
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('orang_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rumah_sakit.Orang')),
                ('keluhan', models.TextField(verbose_name='Keluhan')),
                ('tanggal_periksa', models.DateTimeField()),
            ],
            bases=('rumah_sakit.orang',),
        ),
    ]
