# Generated by Django 2.2.3 on 2019-07-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumah_sakit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokter',
            name='jadwal',
        ),
        migrations.AddField(
            model_name='dokter',
            name='hari_praktik',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], default=None, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dokter',
            name='jam_praktik',
            field=models.TimeField(default=None, verbose_name='jadwal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pasien',
            name='tanggal_periksa',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resep',
            name='kumpulan_obat',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orang',
            name='alamat',
            field=models.TextField(verbose_name='Alamat'),
        ),
        migrations.AlterField(
            model_name='orang',
            name='telp',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='keluhan',
            field=models.TextField(verbose_name='Keluhan'),
        ),
    ]
