# Generated by Django 2.2.3 on 2019-07-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumah_sakit', '0002_auto_20190722_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resep',
            name='total_harga',
            field=models.BigIntegerField(verbose_name='Total harga'),
        ),
    ]
